version: ""

formatter: markdown table

name: AWS ECS cluster

content: |-

  # AWS ECS cluster

  This repository is meant to hold all of the relevant stateful Terraform code
  for for the AWS ECS cluster.

  AWS services used:
  - Amazon Elastic Load Balancer (ALB)
  - Amazon Elastic Container Service (ECS)
  - Amazon Virtual Private Cloud (VPC)

  Application URL: http://aws-ecs-poc-dev-alb-1489551277.us-east-2.elb.amazonaws.com

  ## Pre-commit

  Project maintainers can take advantage of `pre-commit` to automate various
  tasks before commiting changes to repositories. To easily recreate the checks
  that GitHub Actions performs when a pull request is created or updated,
  you can create an alias for your shell.

  Create a folder to cache tflint plugins, avoid repeated API calls, and get faster tflint executions:

  ```bash
  mkdir -p .tflint.d/
  ```

  Add the cache folder to `.gitignore`
  ```bash
  .tflint.d/
  ```

  Create a Personal Access Token in GitHub (Settings > Developer Settings > Personal Access Token), with Read access to metadata permission.

  Set the token as a variable in the shell: 

  ```bash
  read -s '?GitHub token: ' GITHUB_TOKEN; echo; export GITHUB_TOKEN
  ```

  Set the alias for pre-commit-run:

  ```bash
  alias pre-commit-run='docker run --rm \
    -v "$(pwd):/lint" \
    -v "$HOME/.tflint.d:/root/.tflint.d" \
    -w /lint \
    -e GITHUB_TOKEN \
    --entrypoint /bin/sh \
    ghcr.io/antonbabenko/pre-commit-terraform:latest \
    -c "tflint --init && pre-commit run -a"'
  ```
  Run the alias:

  ```bash
  pre-commit-run
  ```

  ## Deployment

  To quickly initialize the current Terraform configuration and create or update
  the associated infrastructure, try the following commands:

  > **_NOTE:_**  You must have a valid AWS session token for the following
  commands to complete successfully.

  ### Development (dev)

  Prepare your working directory for other Terraform commands:
  ```bash
  terraform init -backend-config=./init-tfvars/dev.tfvars
  ```
  Show changes required by the current configuration:
  ```bash
  terraform plan -var-file ./apply-tfvars/dev.tfvars
  ```
  Create or update infrastructure:
  ```bash
  terraform apply -var-file ./apply-tfvars/dev.tfvars
  ```
   
  ## Documentation

  This repo is self documenting via Terraform Docs, please see the note at the
  bottom.

  The `.config/.terraform-docs.yml` file auto generates the `README.md` file

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  > **_NOTE:_**  Manual changes to the README will be overwritten when the
  documentation is updated. To update the documentation, run:
  ```bash
  terraform-docs --config .config/.terraform-docs.yml .
  ```

sections:
  show:
    - requirements
    - resources
    - modules
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace